import 'package:flutter/material.dart';

class AppColors {
  const AppColors._();

  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1E88E5),
    onPrimary: Colors.white,
    primaryContainer: Color(0xFFD1E4FF),
    onPrimaryContainer: Color(0xFF0B2D4E),
    secondary: Color(0xFFFFC107),
    onSecondary: Color(0xFF2C2C2C),
    secondaryContainer: Color(0xFFFFE7A8),
    onSecondaryContainer: Color(0xFF2C2100),
    tertiary: Color(0xFF7E57C2),
    onTertiary: Colors.white,
    tertiaryContainer: Color(0xFFE6D7FF),
    onTertiaryContainer: Color(0xFF2C1A57),
    error: Color(0xFFB00020),
    onError: Colors.white,
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFF7F7FB),
    onSurface: Color(0xFF121212),
    surfaceContainerHighest: Color(0xFFEDECF3),
    onSurfaceVariant: Color(0xFF5A5A66),
    outline: Color(0xFFCAC4D0),
    outlineVariant: Color(0xFFE3E1E8),
    background: Color(0xFFFFFFFF),
    onBackground: Color(0xFF121212),
    surfaceVariant: Color(0xFFE8E7EE),
    inverseSurface: Color(0xFF2C2C2C),
    onInverseSurface: Color(0xFFF0F0F0),
    inversePrimary: Color(0xFF90CAF9),
    shadow: Colors.black12,
    scrim: Colors.black54,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF90CAF9),
    onPrimary: Color(0xFF0B2D4E),
    primaryContainer: Color(0xFF0B2D4E),
    onPrimaryContainer: Color(0xFFD1E4FF),
    secondary: Color(0xFFFFD54F),
    onSecondary: Color(0xFF2C2C2C),
    secondaryContainer: Color(0xFF594300),
    onSecondaryContainer: Color(0xFFFFE7A8),
    tertiary: Color(0xFFB39DDB),
    onTertiary: Color(0xFF2C1A57),
    tertiaryContainer: Color(0xFF2C1A57),
    onTertiaryContainer: Color(0xFFE6D7FF),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF151518),
    onSurface: Color(0xFFEAEAF0),
    surfaceContainerHighest: Color(0xFF1E1E22),
    onSurfaceVariant: Color(0xFFB0B0BD),
    outline: Color(0xFF44434C),
    outlineVariant: Color(0xFF2C2B33),
    background: Color(0xFF0F0F12),
    onBackground: Color(0xFFEAEAF0),
    surfaceVariant: Color(0xFF23222A),
    inverseSurface: Color(0xFFEAEAF0),
    onInverseSurface: Color(0xFF1A1A1D),
    inversePrimary: Color(0xFF1E88E5),
    shadow: Colors.black54,
    scrim: Colors.black87,
  );
}
