// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0zu1YvZEXomPhsdURfgZwmQqQ42RxP4',
    appId: '1:130876239407:web:75042ce9ff0b672ddd20da',
    messagingSenderId: '130876239407',
    projectId: 'badr-movie-app',
    authDomain: 'badr-movie-app.firebaseapp.com',
    storageBucket: 'badr-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjvSkrcs-oGftrWSsJl0ROIV1eUIBFpu4',
    appId: '1:130876239407:android:e53ac61f367fb27add20da',
    messagingSenderId: '130876239407',
    projectId: 'badr-movie-app',
    storageBucket: 'badr-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnU_rCzbifwUYQN7jC--895wpFmQJLVgU',
    appId: '1:130876239407:ios:eebc2f83487f622fdd20da',
    messagingSenderId: '130876239407',
    projectId: 'badr-movie-app',
    storageBucket: 'badr-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.simpleMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnU_rCzbifwUYQN7jC--895wpFmQJLVgU',
    appId: '1:130876239407:ios:eebc2f83487f622fdd20da',
    messagingSenderId: '130876239407',
    projectId: 'badr-movie-app',
    storageBucket: 'badr-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.simpleMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0zu1YvZEXomPhsdURfgZwmQqQ42RxP4',
    appId: '1:130876239407:web:587fcd09ee91141fdd20da',
    messagingSenderId: '130876239407',
    projectId: 'badr-movie-app',
    authDomain: 'badr-movie-app.firebaseapp.com',
    storageBucket: 'badr-movie-app.firebasestorage.app',
  );
}
